import {normalize,matchSpeech} from './matcher.mjs';
const $=id=>document.getElementById(id), ids=['script','language','size','mirror'];
const sample='Вы можете читать в собственном темпе.\n\nВставьте сюда подготовленный текст, выберите голосовой режим и нажмите «Начать чтение».\n\nДелайте паузы, когда это необходимо. Продолжайте говорить, и текущие слова будут выделены цветом.\n\nРазмер текста можно увеличить. Нажмите кнопку полного экрана, чтобы увеличить область чтения.';
let saved={};try{saved=JSON.parse(localStorage.getItem('strela-prompter')||'{}')}catch{};
for(const id of ids)if(saved[id]!==undefined){if(id==='mirror')$(id).checked=saved[id];else $(id).value=saved[id]}
if(saved.script===undefined)$('script').value=sample;
let spans=[],tokens=[],cursor=0,running=false,recognizer=null,epoch=0,retry=null,frame=0,last=0;
const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;
function status(s){$('status').textContent=s}
function save(){const data={};for(const id of ids)data[id]=id==='mirror'?$(id).checked:$(id).value;try{localStorage.setItem('strela-prompter',JSON.stringify(data))}catch{status('Не удалось сохранить текст в браузере')}}
function render(){stop();$('words').replaceChildren();const parts=$('script').value.split(/(\s+)/);spans=[];tokens=[];for(const part of parts){if(!part)continue;if(/^\s+$/.test(part))$('words').append(document.createTextNode(part));else{const span=document.createElement('span');span.textContent=part;$('words').append(span);if(normalize(part)){spans.push(span);tokens.push(normalize(part))}}}cursor=0;$('count').textContent=`${tokens.length} слов · ${$('script').value.length} знаков`;highlight(false);$('viewport').scrollTop=0}
function highlight(scroll=true){spans.forEach((s,i)=>s.className=i<cursor?'past':i===cursor?'active':'');const p=tokens.length?Math.round(cursor/Math.max(1,tokens.length)*100):0;$('progress').textContent=p+'%';$('bar').style.width=p+'%';if(scroll&&spans.length){const view=$('viewport'),r=spans[Math.min(cursor,spans.length-1)].getBoundingClientRect(),v=view.getBoundingClientRect();view.scrollTo({top:view.scrollTop+r.top-v.top-view.clientHeight*.32,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}}
function stop(){running=false;epoch++;clearTimeout(retry);cancelAnimationFrame(frame);if(recognizer){const old=recognizer;recognizer=null;old.onend=null;old.abort()}document.body.classList.remove('running');$('start').textContent='Начать чтение';status('Готов к чтению');$('script').disabled=false}
function listen(ticket){if(!running||ticket!==epoch)return;const rec=new Recognition;recognizer=rec;rec.lang=$('language').value;rec.continuous=true;rec.interimResults=true;let fatal=false;rec.onstart=()=>status('Слушаю · читайте текст');rec.onresult=e=>{for(let i=e.resultIndex;i<e.results.length;i++){const spoken=e.results[i][0].transcript;$('heard').textContent=spoken;const found=matchSpeech(tokens,spoken,cursor);if(found!==null){cursor=found+1;highlight();if(cursor===tokens.length&&e.results[i].isFinal){stop();status('Чтение завершено')}}}};rec.onerror=e=>{if(['not-allowed','service-not-allowed','audio-capture','language-not-supported'].includes(e.error)){fatal=true;stop();status(e.error==='audio-capture'?'Микрофон недоступен':e.error==='language-not-supported'?'Язык не поддерживается браузером':'Доступ к распознаванию запрещён');$('heard').textContent='Разрешите микрофон'}else if(e.error==='network'){fatal=true;stop();status('Ошибка соединения с речевым сервисом')}};rec.onend=()=>{if(!fatal&&running&&ticket===epoch)retry=setTimeout(()=>listen(ticket),400)};try{rec.start()}catch{stop();status('Не удалось запустить распознавание')}}
function start(){if(running){stop();status('Пауза');return}if(!tokens.length){status('Сначала вставьте текст');$('script').focus();return}if(!Recognition){status('Голосовой режим недоступен в этом браузере');$('heard').textContent='Откройте страницу в Chrome или Edge';return}running=true;document.body.classList.add('running');$('script').disabled=true;$('start').textContent='Приостановить';highlight();listen(++epoch)}
function settings(){ $('words').style.fontSize=$('size').value+'px';$('sizeValue').value=$('size').value+' px';document.querySelector('.preview').classList.toggle('mirrored',$('mirror').checked);}
for(const id of ids)$(id).addEventListener('input',()=>{if(id==='script')render();if(id==='language')stop();settings();save()});
$('start').onclick=start;$('reset').onclick=()=>{stop();cursor=0;highlight();$('heard').textContent='Пробел: пауза · ↓: следующая строка'};
function move(direction){const start=cursor,top=spans[start]?.offsetTop;let i=start+direction;while(i>=0&&i<spans.length&&spans[i].offsetTop===top)i+=direction;cursor=Math.max(0,Math.min(spans.length-1,i));highlight()}
$('next').onclick=()=>move(1);$('back').onclick=()=>move(-1);
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.querySelector('.preview').requestFullscreen()}catch{status('Полный экран недоступен')}};
$('import').onclick=()=>$('file').click();$('file').onchange=async()=>{const file=$('file').files[0];if(file){$('script').value=await file.text();render();save()}$('file').value=''};
document.addEventListener('keydown',e=>{if(['TEXTAREA','INPUT','SELECT','BUTTON'].includes(e.target.tagName)||e.ctrlKey||e.metaKey||e.altKey)return;if(e.code==='Space'){e.preventDefault();start()}if(e.code==='ArrowDown'){e.preventDefault();move(1)}if(e.code==='ArrowUp'){e.preventDefault();move(-1)}if(e.code==='Escape'&&running)stop()});
settings();render();
